config/routes.rb
Rails.application.routes.draw do
  match "/login" => "authentications#signin", :as => :login
  match "/logout" => "authentications#signout", :as => :logout
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  
  resources :authentications, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :login_from_cookie
  helper_method :current_user, :logged_in?
  
  protected
     
  def current_user
    @current_user ||= Identity.find_by_id(session[:identity])
  end
  
  def current_user=(identity)
    session[:identity] = identity.id
  end
  
  def logged_in?
    !self.current_user.nil?
  end
  
  def login_required
    return true if logged_in?
    flash[:notice] = 'Please login to do this'
    redirect_to login_path
    false
  end   
  
  def login_from_cookie
    return unless cookies[:token] && !logged_in?
    identity = Identity.find_by_token(cookies[:token])
    if identity && identity.token?
      self.current_user = identity
    else
      clear_cookies
    end
  end
  
  def clear_cookies
    cookies.delete :token
  end
end

app/views/authentications/new.html.erb
<div class="services" id="services_signin">
  <%= form_tag "/auth/identity/callback" do %>
    <div class="field">
      <%= label_tag :auth_key, "Email" %><br>
      <%= text_field_tag :auth_key %>
    </div>
    <div class="field">
      <%= label_tag :password %><br>
      <%= password_field_tag :password %>
    </div>
    <div class="actions"><%= submit_tag "Login" %></div>
  <% end %>
</div>

app/views/authentications/signin.html.erb
<div class="login_wrapper">
  <h1>Sign In</h1>
  <%= form_tag "/auth/identity/callback" do %>
    <div class="field">
      <%= label_tag :auth_key, "Email" %><br>
      <%= text_field_tag :auth_key %>
    </div>
    <div class="field">
      <%= label_tag :password %><br>
      <%= password_field_tag :password %>
    </div>
    <div class="actions"><%= submit_tag "Login" %></div>
  <% end %>

  <p><strong>Sign in through Google Account:</strong></p>
  <div class="auth_providers">
    <a href="/auth/google_oauth2" class="auth_provider">
      <%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %>
      Google
    </a>
  </div>
</div>

app/views/authentications/signup.html.erb
<section id="services_new" class="services">
	<h1>Create New Account</h1>

	<div>
		<h3>This authentication is new to PEWGRF</h3>
		
		<p class="small">
			Provider: <%= @authhash[:provider] %><br />
			ID: <%= @authhash[:uid] %><br />
			Name: <%= @authhash[:name] %><br />
			Email: <%= @authhash[:email] %>	<br />
		</p>

		<%= form_tag newaccount_authentications_path, :method => :post do %>
			<%= submit_tag "Confirm and create new account" %> <%= submit_tag "Cancel" %>
		<% end %>
	</div>
</section>